# Uncomment the next line to define a global platform for your project
platform :ios, '10.3'

target 'MisRecuerdos' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MisRecuerdos
  pod 'INSPhotoGallery', ‘1.1.0’
  pod ‘INSNibLoading’, ‘1.0.2’

end
